version: "3"
services:
  traefik: 
    command: "--web --docker --logLevel=INFO"
    image: traefik
    ports: 
      - "80:80"
      - "8080:8080"
    labels:
      - traefik.frontend.auth.forward.address=http://192.168.1.3:16000/auth
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./traefik.toml:/traefik.toml
  whitemos: 
    image: jasonsoft/whitemos
    ports: 
      - "10080:10080"
    labels: 
      - "traefik.enable=true"
      - traefik.backend=whoami
      - "traefik.frontend.rule=PathPrefixStrip:/test1"
      - "traefik.frontend.rateLimit.extractorFunc=client.ip"
      # 五秒三個 Requests
      - "traefik.frontend.rateLimit.rateSet.r1.period=5s"
      - "traefik.frontend.rateLimit.rateSet.r1.average=1"
      - "traefik.frontend.rateLimit.rateSet.r1.burst=3"
  whoami2: 
    image: emilevauge/whoami
    labels: 
      - "traefik.enable=true"
      - traefik.backend=whoami2
      - "traefik.frontend.rule=Path:/test2"
      - traefik.frontend.auth.forward.address=http://192.168.1.3:16000/auth
      - "traefik.frontend.auth.forward.authResponseHeaders=X-Auth-JWT"
  nginx: 
    image: nginx
    ports: 
      - "10066:80"
    labels: 
      - "traefik.enable=true"
      - traefik.backend=nginx
      - "traefik.frontend.rule=PathPrefixStrip:/test3"